# Generated by Django 6.0.4 on 2026-06-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bonus_points_user_orders_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bonus_points',
        ),
    ]
