# Generated by Django 6.0.4 on 2026-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_product_cart_pizza_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('30', '30 см'), ('35', '35 см'), ('40', '40 см')], default='30', max_length=2, verbose_name='Размер'),
        ),
    ]
