# Generated by Django 6.0.4 on 2026-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'Processing'), ('Доставлен', 'Delivered'), ('Отменён', 'Cancelled')], default='В обработке', max_length=20, verbose_name='Статус'),
        ),
    ]
