# Generated by Django 6.0.4 on 2026-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Картой при получении')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
