# Generated by Django 6.0.4 on 2026-04-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пиццы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_30', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена 30 см')),
                ('price_35', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена 35 см')),
                ('price_40', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена 40 см')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Острая')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианская')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['order', 'name'],
            },
        ),
    ]
