# Generated by Django 6.0.4 on 2026-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pizza_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/', verbose_name='Изображение'),
        ),
    ]
